# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32, verbose_name='name')),
                ('u_phonenum', models.CharField(max_length=20, unique=True, verbose_name='phone')),
                ('u_sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=8, verbose_name='sex')),
                ('u_birthday', models.DateField(default='1990-1-1', verbose_name='birthday')),
                ('u_avatar', models.CharField(max_length=256, verbose_name='avatar')),
                ('u_location', models.CharField(choices=[('Shanghai', 'shanghai'), ('Beijing', 'beijing'), ('Guangdong', 'guangdong'), ('Jiangsu', 'jiangsu'), ('Anhui', 'anhui'), ('Hunan', 'hunan'), ('Henan', 'hunan')], default='Beijing', max_length=16, verbose_name='location')),
            ],
            options={
                'db_table': 'user_module',
            },
        ),
    ]
