# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=8)),
                ('locations', models.CharField(choices=[('Shanghai', 'shanghai'), ('Beijing', 'beijing'), ('Guangdong', 'guangdong'), ('Jiangsu', 'jiangsu'), ('Anhui', 'anhui'), ('Hunan', 'hunan'), ('Henan', 'hunan')], max_length=16)),
                ('min_distance', models.IntegerField(default=1)),
                ('max_distance', models.IntegerField(default=30)),
                ('min_dating_age', models.IntegerField(default=18)),
                ('max_dating_age', models.IntegerField(default=30)),
                ('vibration', models.BooleanField(default=True)),
                ('only_matche', models.BooleanField(default=True)),
                ('auto_play', models.BooleanField(default=True)),
            ],
        ),
    ]
