# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16)),
                ('u_password', models.CharField(max_length=16)),
                ('u_sex', models.CharField(max_length=3)),
                ('u_phonenum', models.CharField(max_length=13)),
                ('u_birthday', models.DateField()),
                ('u_location', models.CharField(max_length=16)),
                ('u_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
